### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'encode')` on line 14 of graph.js

### ISSUE THREAD

**Issue by ChristianOConnor** [chainstack/ethereum-token-balances#3]
I don't know why this is happening but this is my terminal error:  
```
<myusername>@<mycomputername> token-balance-through-time % node graph.js 
/Users/<myusername>/Desktop/Dev/token-balance-through-time/graph.js:14
  const callData = ethersInterface.functions.balanceOf.encode([walletAddress]);
                                                       ^

TypeError: Cannot read properties of undefined (reading 'encode')
    at retrieveTokenBalanceViaGraphQL (/Users/<myusername>/Desktop/Dev/token-balance-through-time/graph.js:14:56)
    at main (/Users/<myusername>/Desktop/Dev/token-balance-through-time/graph.js:35:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
<myusername>@<mycomputername> token-balance-through-time % 
```

**Comment by uF4No** [comment]
Hi

I'm not able to replicate the issue. 

Just to make sure, have you installed all dependencies first running `npm i` and configured your wallet address, graphql endpoint, username, and password in the `constant.js` file?

Keep in mind that GraphQL is only available on dedicated nodes 😉
